server:
  port: 9002

# Add color to run Spring boot
spring:
  output:
      ansi:
          enabled: always

resilience4j.circuitbreaker:
  instances:
    FLOWERS:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
